// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCarxDGDxtydziDEWVxoi2yUQG6uQSZY',
    appId: '1:71129436311:android:ab1692d5071b89c7a299d2',
    messagingSenderId: '71129436311',
    projectId: 'flutter-messager-39380',
    databaseURL: 'https://flutter-messager-39380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messager-39380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocAyZ9wRnMZSwefBedwZ21ItSSXh759U',
    appId: '1:71129436311:ios:1dc8c4595272af44a299d2',
    messagingSenderId: '71129436311',
    projectId: 'flutter-messager-39380',
    databaseURL: 'https://flutter-messager-39380-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messager-39380.appspot.com',
    iosClientId: '71129436311-3utvcegvgn8rv5olvjgn70hrl2uuc4i6.apps.googleusercontent.com',
    iosBundleId: 'net.cyberplanete.flutterMessagerV2',
  );
}
